apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: qi5xo4ojt-go
  janus-idp.io/tekton: qi5xo4ojt-go
  backstage.io/kubernetes-id: qi5xo4ojt-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: qi5xo4ojt-go
resources:
- deployment.yaml
- route.yaml
- service.yaml
